config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
      get :feeds
      get :ranking
    end


     member do
      get :dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
     end

  end

  resources :users, only: [:index, :show, :edit, :update] do
     member do
      get :friend_list
    end
  end
  
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :categories, only: :show

  root "restaurants#index"

   namespace :admin do
     resources :restaurants
     resources :categories
     root "restaurants#index"
   end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   validates_presence_of :name, :email
  #  :intro, :avatar

    mount_uploader :avatar, AvatarUploader
    has_many :comments, dependent: :restrict_with_error
    has_many :restaurants, through: :comments


    has_many :favorites, dependent: :destroy
    has_many :favorited_restaurants, through: :favorites, source: :restaurant

    has_many :likes, dependent: :destroy
    has_many :liked_restaurants, through: :likes, source: :restaurant

    has_many :followships, dependent: :destroy
    has_many :followings, through: :followships

    has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
    has_many :followers, through: :inverse_followships, source: :user

    has_many :friendships, dependent: :destroy
    has_many :friends, through: :friendships

    has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
    has_many :inverse_friends, through: :inverse_friendships, source: :user



    def admin?
       self.role == "admin"
    end

    def following?(user)
      self.followings.include?(user)
    end

    def all_friends
      (friends + inverse_friends).uniq
    end

    def friend?(user)
      # self.friends.include?(user)
      all_friends.include?(user)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :friend_list]


  def index

    @users = User.all
  end


  def show

    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.restaurants
    @followings = @user.followings
    @followers = @user.followers
  end

  def edit

     unless @user == current_user
       redirect_to user_path(@user)
     end
  end


  def update

     if @user.update_attributes(user_params)
       redirect_to user_path(@user)
     else
       render :action => :edit
     end
  end


  def friend_list

      @friends = @user.all_friends

  end



  private

     def set_user
        @user = User.find(params[:id])
      end

     def user_params
       params.require(:user).permit(:name, :intro, :avatar)
     end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
   <div class="col-md-6 col-md-offset-3">
    <% if @user.errors.any? %>
      <h4>We have some errors here !</h4>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <hr>
     <% end %>
     <!-- <% if @user.errors.present? %>
       <ul>
         <% @user.errors.each do |error, message| %>
           <li> <%= "#{error.capitalize}  #{message}" %></li>
         <% end %>
       </ul>
     <% end %> -->


    <h2> Edit Profile </h2>
    <tr>
    <%= form_for [@user] do |f| %>
      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>


      <div class="form-group">
        <%= f.label :intro, "About you" %>
        <%= f.text_area :intro, class: "form-control" %>
      </div>


      <div class="form-group">
        <%= f.label :avatar, "Avatar" %>
        <%= image_tag @user.avatar if @user.avatar? %>
        <%= f.file_field :avatar %>
      </div>

      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
      </div>
    <% end %>

   </div>
  </div>
</div>

app/views/users/friend_list.html.erb
<div class="container">
   <div class="row">
   <h2> Friend List </h2>
   <br>
<% @friends.each do |friend| %>
  <div class="col-md-3 col-sm-4 col-xs-6 text-center user-item">

    <%= link_to user_path(friend) do %>
    <% if friend.avatar? %>
      <%= image_tag friend.avatar, class: "img-circle", size: "50" %>
    <% else %>
      <%= image_tag "http://via.placeholder.com/120x120", class: "img-responsive center-block img-rounded"  %>
    <% end %>


     <h4><%= friend.name %></h4>
   <% end %>



    <%= render partial: "shared/follow", locals: {user: @user} %>

    <%= render partial: "shared/friend", locals: {user: @user} %>




   </div>
<% end %>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
   <div class="row">


     <ul class="nav nav-tabs">
        <li role="presentation" >
         <%= link_to '首頁', root_path %>
       </li>
        <li role="presentation">
         <%= link_to '最新動態', feeds_restaurants_path %>
       </li>
        <li role="presentation">
         <%= link_to 'TOP10 人氣餐廳', ranking_restaurants_path %>
       </li>
       <li role="presentation" class="active">
        <%= link_to '美食達人', users_path %>
      </li>
     </ul>

   </div>
 </div>

   <br>
  <div class="container">
    <div class="row">
           <div class="col-md-12">
             <div class="page-header">
               <h1>美食達人</h1>
             </div>
           </div>

       <ul>

        <% @users.each do |user| %>
          <div class="col-md-3 col-sm-4 col-xs-6 text-center user-item">

            <%= link_to user_path(user) do %>
            <% if user.avatar? %>
              <%= image_tag user.avatar, class: "img-circle", size: "50" %>
            <% else %>
              <%= image_tag "http://via.placeholder.com/120x120", class: "img-responsive center-block img-rounded"  %>
            <% end %>

             <!-- <%= image_tag(user.avatar, class: "img-responsive") %> -->
              <h4><%= user.name %></h4>
           <% end %>

            <%= render partial: "shared/follow", locals: {user: user} %>

            <%= render partial: "shared/friend", locals: {user: user} %>


           </div>
        <% end %>

       </ul>
   </div>
</div>

app/views/users/show.html.erb
<div class="container">
   <div class="row">
     <div class="col-md-10 col-md-offset-1">


       <div class="page-header">
       
         <div class="col-md-3 col-sm-4">
           <div class="text-center">
             <%= image_tag @user.avatar, class: "img-responsive img-rounded" %>
           </div>
         </div>

         <div class="col-md-9 col-sm-8">
           <h2><%= @user.name %></h2>
           <p><strong><%= @user.email %></strong></p>
           <ul class="list-unstyled list-inline">
             <li><strong><%= @commented_restaurants.size %></strong> 已評論餐廳</li>
             <li><strong><%= @favorited_restaurants.size %></strong> 收藏的餐廳</li>
             <li><strong><%= @followings.count %></strong> Following</li>
             <li><strong><%= @followers.count %></strong> Follower</li>
           </ul>
           <div><%= simple_format @user.intro %></div>
           <% if @user.email == current_user.email %>
             <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-info" %>
             <%= link_to 'Friend List', friend_list_user_path(@user), class: "btn btn-info" %>
             <%= link_to 'Edit Password',edit_user_registration_path, class: "nav-text btn btn-info" %>

           <% end %>
         </div>

         <div class="clearfix"></div>

       </div>
       <br>


       <!-- <div class="container">
          <div class="row">
           <div class="col-md-12 col-md-offset-1"> -->





              <div class="col-md-9 col-sm-8">

              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title"><strong><%= @commented_restaurants.count %></strong> 已評論餐廳</h3>
                </div>
                <div class="panel-body">
                  <% @commented_restaurants.each do |restaurant| %>

                  <%= link_to restaurant_path(restaurant) do %>
                  <div class="my-restaurant">
                    <div>
                      <% if restaurant.image? %>
                        <%= image_tag restaurant.image, class: "img-rounded img-responsive" %>
                      <% else %>
                        <img src="http://via.placeholder.com/90x60" class="img-rounded img-responsive">
                      <% end %>


                    </div>
                    <h5><%= restaurant.name %></h5>
                  </div>
                  <% end %>

                  <% end %>
                </div>
              </div>

              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title"><strong><%= @favorited_restaurants.count %></strong> 收藏的餐廳</h3>
                </div>
                <div class="panel-body">
                  <% @favorited_restaurants.each do |restaurant| %>

                  <%= link_to restaurant_path(restaurant) do %>
                  <div class="my-restaurant">
                    <div>

                        <% if restaurant.image? %>
                          <%= image_tag restaurant.image, class: "img-rounded img-responsive" %>
                        <% else %>
                          <img src="http://via.placeholder.com/90x60" class="img-rounded img-responsive">

                        <% end %>




                        <h5><%= restaurant.name %></h5>

                      <div class="text-center">
                      <%= render partial: 'shared/favorite', locals: { restaurant: restaurant } %>
                      </div>
                     </div>

                    </div>
                  <% end %>

                  <% end %>
                </div>
              </div>

            </div>


            <div class="col-md-3 col-sm-4">

              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title"><strong><%= @followings.count %></strong> Followings</h3>
                </div>
                <div class="panel-body">
                  <% @followings.each do |following| %>

                  <%= link_to user_path(following) do %>
                   <div class="my-restaurant">
                    <div>
                      <% if following.avatar? %>
                        <%= image_tag following.avatar, class: "img-circle", size: "80" %>
                      <% else %>
                        <img src="http://via.placeholder.com/80x80" class="img-circle">
                      <% end %>

                      <!-- <%= image_tag(following.avatar, height: 30, width: 30, class: "img-circle") %> -->
                      <!-- <%= image_tag "http://via.placeholder.com/120x120", class: "img-responsive center-block img-rounded"  %> -->
                    </div>
                    <h5><%= following.name %></h5>
                    <%= link_to 'Unfollow', user_path(following), method: :delete, class:"btn btn-info"%>

                  </div>
                  <% end %>

                  <% end %>
                </div>
              </div>


              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title"><strong><%= @followers.count %></strong> Followers</h3>
                </div>
                <div class="panel-body">
                  <% @followers.each do |follower| %>

                  <%= link_to user_path(follower) do %>
                   <div class="my-restaurant">
                    <div>
                      <% if follower.avatar? %>
                        <%= image_tag follower.avatar, class: "img-circle", size: "80" %>
                      <% else %>
                        <img src="http://via.placeholder.com/80x80" class="img-circle">
                      <% end %>
                      <!-- <%= image_tag(follower.avatar, height: 30, width: 30, class: "img-circle") %> -->
                      <!-- <%= image_tag "http://via.placeholder.com/120x120", class: "img-responsive center-block img-rounded"  %> -->
                    </div>
                    <h5><%= follower.name %></h5>
                  </div>
                  <% end %>

                  <% end %>
                </div>
              </div>
              </div>






                <div class="clearfix"></div>

              </div>
            </div>
          <!-- </div>
        </div>
      </div> -->