config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
      get :feeds
      get :ranking
    end


     member do
      get :dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
     end

  end

  resources :users, only: [:index, :show, :edit, :update] do
     member do
      get :friend_list
    end
  end
  
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :categories, only: :show

  root "restaurants#index"

   namespace :admin do
     resources :restaurants
     resources :categories
     root "restaurants#index"
   end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader
  belongs_to :category#, optional: true
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end


  def is_liked?(user)
   self.liked_users.include?(user)
  end

  # def favorites_count
  #  self.favorites_users.count=self.favorites.size
  #  self.save
  # end
  

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController


  before_action :set_restaurant, only:  [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
     
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "restaurant was successfully created"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to create"
      render :new
    end
  end

  def show

  end

  def edit
  end

  def update
      if @restaurant.update(restaurant_params)
        redirect_to admin_restaurant_path(@restaurant)
        flash[:notice] = "restaurant was successfully updated"
      else
        render :edit
        flash[:alert] = "restaurant was failed to update"
      end
    end


    def destroy
        @restaurant.destroy
        redirect_to admin_restaurants_path
        flash[:alert] = "restaurant was deleted"
    end



  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end

  def set_restaurant
     @restaurant = Restaurant.find(params[:id])
   end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :dashboard, :favorite, :unfavorite, :like, :unlike]

  def index
     @restaurants = Restaurant.page(params[:page]).per(9)
     @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new(content: params[:comment])
  end

  def feeds
      @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
      @recent_comments = Comment.order(created_at: :desc).limit(10)
  end


  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

  def ranking
      @restaurants = Restaurant.order(favorites_count: :desc).limit(10)

  end

  def favorite
      @restaurant = Restaurant.find(params[:id])
      @restaurant.favorites.create!(user: current_user)
      favorites_count
      redirect_back(fallback_location: root_path)

  end


  def unfavorite
      @restaurant = Restaurant.find(params[:id])
      favorite = Favorite.where(restaurant: @restaurant, user: current_user)
      favorite.destroy_all
      favorites_count
      redirect_back(fallback_location: root_path)
  end

  def like
      @restaurant = Restaurant.find(params[:id])
      @restaurant.likes.create!(user: current_user)
      redirect_back(fallback_location: root_path)
  end

  def unlike
      @restaurant = Restaurant.find(params[:id])
      like = Like.where(restaurant: @restaurant, user: current_user)
      like.destroy_all
      redirect_back(fallback_location: root_path)
  end



private

   def set_restaurant
      @restaurant = Restaurant.find(params[:id])
   end

  def favorites_count
    @restaurant.favorites_count = @restaurant.favorited_users.count
    @restaurant.save!
  end


end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
 <div class="container">
   <div class="row">

     <% if @restaurant.errors.any? %>
       <h4>We have some errors here !</h4>
       <ul>
         <% @restaurant.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
       <hr>
      <% end %>


     <%= form_for [:admin, @restaurant] do |f| %>

     <div class="form-group">
       <%= f.label :category, "Category" %>
       <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: true}, {class: "form-control"} %>
     </div>


       <div class="form-group">
         <%= f.label :name, "Name" %>
         <%= f.text_field :name, class: "form-control" %>
       </div>


       <div class="form-group">
         <%= f.label :tel, "Tel" %>
         <%= f.text_field :tel, class: "form-control" %>
       </div>


       <div class="form-group">
         <%= f.label :address, "Address" %>
         <%= f.text_field :address, class: "form-control" %>
       </div>


       <div class="form-group">
         <%= f.label :opening_hours, "Opening Hours" %>
         <%= f.text_field :opening_hours, class: "form-control" %>
       </div>


       <div class="form-group">
         <%= f.label :description, "Description" %>
         <%= f.text_area :description, class: "form-control" %>
       </div>


       <div class="form-group">
         <%= f.label :image, "Photo" %>
         <%= image_tag @restaurant.image, width: '300px' if @restaurant.image? %>
         <%= f.file_field :image %>
       </div>

       <div class="form-group">
         <%= f.submit class: "btn btn-info" %>
       </div>
     <% end %>


   </div>
 </div>

app/views/admin/restaurants/edit.html.erb
<%= render partial: "form" %>

app/views/admin/restaurants/index.html.erb
<div class="container">

   <h1>Restaurant Backend</h1>

   <div>
     <%= link_to 'Restaurant', admin_restaurants_path %> |
     <%= link_to 'Categories', admin_categories_path %>
   </div>
   <br>
   <div class="row">

     <div class="col-md-12">

       <div>
         <%= link_to 'New Restaurant', new_admin_restaurant_path, class: "btn btn-info" %>

       </div>

       <br>
       <table class="table table-bordered">
         <thead>
           <tr>
             <th>#</th>
             <th>Category</th>
             <th>Name</th>
             <th>#</th>
           </tr>
         </thead>
         <tbody>
           <% @restaurants.each do |restaurant| %>
           <tr>
             <th scope="row"><%= restaurant.id %></th>
             <td>[<%= restaurant.category.name %>]</td>
             <td><%= restaurant.name %></td>
             <td>


               <%= link_to '<span class="glyphicon glyphicon-list-alt"></span>'.html_safe, admin_restaurant_path(restaurant), class: "btn btn-info" %>
               <%= link_to '<span class="glyphicon glyphicon-edit"</span>'.html_safe, edit_admin_restaurant_path(restaurant), class: "btn btn-info" %>
               <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, admin_restaurant_path(restaurant),method: :delete, data:{ confirm: "Are you sure ?"}, class: "btn btn-info" %>

             </td>
           </tr>
           <% end %>
         </tbody>
       </table>

       <div class="text-center">
         <%= paginate @restaurants %>
       </div>

     </div>

   </div>
 </div>

app/views/admin/restaurants/new.html.erb
<%= render partial: "form" %>

app/views/admin/restaurants/show.html.erb
<div class="container">
  <div class="row">
     <div class="col-md-12">
       <h1><%= @restaurant.name %></h1>
       <%= @restaurant.category.name %>
     </div>


    <div class="col-md-4">
        <%= image_tag @restaurant.image, class: "img-responsive center-block" %>
        <br>
        <div class="well">
          <ul class="list-unstyled">
            <li><strong>Opening Hour:</strong> <%= @restaurant.opening_hours %></li>
            <li><strong>Tel:</strong> <%= @restaurant.tel %></li>
            <li><strong>Address:</strong> <%= @restaurant.address %></li>
          </ul>
        </div>
      </div>
      <div class="col-md-8">
        <%= simple_format @restaurant.description %>
      </div>

  <div class="clearfix"></div>


   <hr>


  </div>

</div>