config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
      get :feeds
      get :ranking
    end


     member do
      get :dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
     end

  end

  resources :users, only: [:index, :show, :edit, :update] do
     member do
      get :friend_list
    end
  end
  
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :categories, only: :show

  root "restaurants#index"

   namespace :admin do
     resources :restaurants
     resources :categories
     root "restaurants#index"
   end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader
  belongs_to :category#, optional: true
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end


  def is_liked?(user)
   self.liked_users.include?(user)
  end

  # def favorites_count
  #  self.favorites_users.count=self.favorites.size
  #  self.save
  # end
  

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController


  before_action :set_restaurant, only:  [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
     
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "restaurant was successfully created"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to create"
      render :new
    end
  end

  def show

  end

  def edit
  end

  def update
      if @restaurant.update(restaurant_params)
        redirect_to admin_restaurant_path(@restaurant)
        flash[:notice] = "restaurant was successfully updated"
      else
        render :edit
        flash[:alert] = "restaurant was failed to update"
      end
    end


    def destroy
        @restaurant.destroy
        redirect_to admin_restaurants_path
        flash[:alert] = "restaurant was deleted"
    end



  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end

  def set_restaurant
     @restaurant = Restaurant.find(params[:id])
   end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :dashboard, :favorite, :unfavorite, :like, :unlike]

  def index
     @restaurants = Restaurant.page(params[:page]).per(9)
     @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new(content: params[:comment])
  end

  def feeds
      @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
      @recent_comments = Comment.order(created_at: :desc).limit(10)
  end


  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

  def ranking
      @restaurants = Restaurant.order(favorites_count: :desc).limit(10)

  end

  def favorite
      @restaurant = Restaurant.find(params[:id])
      @restaurant.favorites.create!(user: current_user)
      favorites_count
      redirect_back(fallback_location: root_path)

  end


  def unfavorite
      @restaurant = Restaurant.find(params[:id])
      favorite = Favorite.where(restaurant: @restaurant, user: current_user)
      favorite.destroy_all
      favorites_count
      redirect_back(fallback_location: root_path)
  end

  def like
      @restaurant = Restaurant.find(params[:id])
      @restaurant.likes.create!(user: current_user)
      redirect_back(fallback_location: root_path)
  end

  def unlike
      @restaurant = Restaurant.find(params[:id])
      like = Like.where(restaurant: @restaurant, user: current_user)
      like.destroy_all
      redirect_back(fallback_location: root_path)
  end



private

   def set_restaurant
      @restaurant = Restaurant.find(params[:id])
   end

  def favorites_count
    @restaurant.favorites_count = @restaurant.favorited_users.count
    @restaurant.save!
  end


end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/dashboard.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-12">
    <h1><%= @restaurant.name %>'s Dashboard</h1>
    <hr>
        <ul>
          <li>有 <%= @restaurant.comments.count %> 筆評論</li>
          <li>這家餐廳的平均價位為 $XXX</li>
          <li>有 XX 人收藏這家餐廳</li>
        </ul>
    </div>
  </div>
</div>

app/views/restaurants/feeds.html.erb
<div class="container">
<div class="row">


  <ul class="nav nav-tabs">
     <li role="presentation">
       <%= link_to '首頁', root_path %>
     </li>
     <li role="presentation" class="active">
       <%= link_to '最新動態', feeds_restaurants_path %>
     </li>
     <li role="presentation">
       <%= link_to 'TOP10 人氣餐廳', ranking_restaurants_path %>
     </li>
     <li role="presentation">
      <%= link_to '追蹤的美食達人', ranking_restaurants_path %>
    </li>
   </ul>
</div>

<br>

 <div class="container">
 <div class="row">
<div class="col-md-10 col-md-offset-1">

<h1>餐廳最新動態</h1>
<hr>

    <div class="col-md-6">
         <div class="panel panel-default">
           <div class="panel-heading">最新餐廳</div>
           <div class="panel-body">
             <% @recent_restaurants.each do |restaurant| %>
               <div>

                  <h4>
                   <%= link_to restaurant.name, restaurant_path(restaurant) %>
                   <small><%= restaurant.category.name %></small>
                 </h4>
                 <p><%= truncate(restaurant.description, length: 80) %></p>
                 <hr>
               </div>
             <% end %>

           </div>
         </div>
       </div>

       <div class="col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">最新評論</div>
              <div class="panel-body">
                <% @recent_comments.each do |comment| %>
                  <div>

                    <h4>
                      <%= link_to comment.restaurant.name, restaurant_path(comment.restaurant) %>
                    </h4>
                    <p><%= truncate(comment.content, length: 80) %><small > - by <%= link_to comment.user.name, user_path(comment.user) %></small></p>
                    <hr>
                    <div class="clearfix"></div>
                  </div>
                <% end %>

              </div>
            </div>
          </div>
        </div>

     </div>
   </div>

app/views/restaurants/index.html.erb
<div class="container">
   <div class="row">


     <ul class="nav nav-tabs">
        <li role="presentation" class="active">
         <%= link_to '首頁', root_path %>
       </li>
        <li role="presentation">
         <%= link_to '最新動態', feeds_restaurants_path %>
       </li>
        <li role="presentation">
         <%= link_to 'TOP10 人氣餐廳', ranking_restaurants_path %>
       </li>
       <li role="presentation">
        <%= link_to '美食達人', users_path %>
      </li>
     </ul>

   </div>
 </div>

 <br>
<div class="container">
  <div class="row">

    <ul class="nav nav-pills nav-pills-center">
      <li role="presentation" class="active"><%= link_to "全部餐廳", root_path %></li>
      <% @categories.each do |category| %>
        <li role="presentation"><%= link_to category.name, category_path(category) %></li>
      <% end %>
    </ul>

    <br>


    <%= render partial: "shared/restaurant_list" %>




  </div>
</div>

app/views/restaurants/ranking.html.erb
<div class="container">
<div class="row">


  <ul class="nav nav-tabs">
    <li role="presentation">
      <%= link_to '首頁', root_path %>
    </li>
    <li role="presentation">
      <%= link_to '最新動態', feeds_restaurants_path %>
    </li>
    <li role="presentation" class="active">
      <%= link_to 'TOP10 人氣餐廳', ranking_restaurants_path %>
    </li>
    <li role="presentation">
     <%= link_to '美食達人', users_path %>
   </li>
  </ul>

<br>

 <div class="container">
  <div class="row">
   <div class="col-md-10 col-md-offset-1">
    <div class="page-header">
      <h1>TOP10 人氣餐廳</h1>
    </div>


<hr>

    <div class="col-md-10">
         <!-- <div class="panel panel-default">
           <div class="panel-heading"></div>
           <div class="panel-body"> -->
             <% @restaurants.each do |restaurant| %>
               <div>
                 <div class="ranking-item">
                   <div class="col-md-3">
                     <%= link_to restaurant_path(restaurant) do %>
                       <% if restaurant.image? %>
                         <%= image_tag restaurant.image, class: "img-responsive center-block" %>
                       <% else %>
                         <img src="http://via.placeholder.com/90x60" class="img-rounded img-responsive">
                       <% end %>
                   <!-- <%= image_tag restaurant.image, class: "img-responsive center-block"  %> -->
                 <% end %>
               </div>
               <div class="col-md-9">
                 <h4>
                   <%= link_to restaurant.name, restaurant_path(restaurant) %>
                    <span class="label label-default">收藏數：<%= restaurant.favorites_count %></span>
                   <small><%= restaurant.category.name %></small>
                 </h4>
                 <p><%= truncate(restaurant.description, length: 200) %></p>
                 <%= link_to 'Show', restaurant_path(restaurant), class: "btn btn-info" %>
                 <%= render partial: 'shared/favorite', locals: { restaurant: restaurant } %>
                 <%= render partial: 'shared/like', locals: { restaurant: restaurant } %>
                 <hr>
                 <div class="clearfix"></div>
               </div>
             <% end %>
             <!-- </div>
           </div>
         </div> -->
       </div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
      <p>[<%= @restaurant.category.name %>]</p>
    </div>

    <div class="col-md-4">
      <%= image_tag @restaurant.image, class: "img-responsive center-block" %>
      <br>
      <div class="well">
        <ul class="list-unstyled">
          <li><strong>Opening Hour:</strong> <%= @restaurant.opening_hours %></li>
          <li><strong>Tel:</strong> <%= @restaurant.tel %></li>
          <li><strong>Address:</strong> <%= @restaurant.address %></li>
        </ul>
      </div>
    </div>
    <div class="col-md-8">
      <%= simple_format @restaurant.description %>

      <hr>
       <%= link_to 'Dashboard', dashboard_restaurant_path(@restaurant), class: "btn btn-primary" %>

       <%= render partial: "shared/favorite", locals: {restaurant: @restaurant} %>
       <%= render partial: "shared/like", locals: {restaurant: @restaurant} %>
       
    </div>

    <div class="clearfix"></div>

    <hr>

  </div>

<div class="container">
  <div class="row">
   <%= form_for [@restaurant, @comment] do |f| %>
    <div class="form-group">
      <%= f.text_area :content, placeholder: "留個言吧", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
      <%= f.button "Cancel", type: :reset, class: "btn btn-default" %>
    </div>
  <% end %>
  </div>
</div>
<% @restaurant.comments.each do |comment| %>
    <div>
      <h4><%= comment.user.name%></h4>
      <p><%= simple_format comment.content %></p>
      <p class="text-muted">
        <em><%= time_ago_in_words(comment.created_at) %> </em>

      </p>
      <% if current_user.admin? %>
          <%= link_to "Delete", restaurant_comment_path(@restaurant, comment), method: :delete %>
        <% end %>
    </div>
    <hr>
    <% end %>
</div>