config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
      get :feeds
      get :ranking
    end


     member do
      get :dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
     end

  end

  resources :users, only: [:index, :show, :edit, :update] do
     member do
      get :friend_list
    end
  end
  
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :categories, only: :show

  root "restaurants#index"

   namespace :admin do
     resources :restaurants
     resources :categories
     root "restaurants#index"
   end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name

  has_many :restaurants, dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/favorite.rb
class Favorite < ApplicationRecord
   belongs_to :user
   belongs_to :restaurant#, counter_cache: true

end

app/models/followship.rb
class Followship < ApplicationRecord
   belongs_to :user
   belongs_to :following, class_name: "User"
   validates :following_id, uniqueness: { scope: :user_id }

   

end

app/models/friendship.rb
class Friendship < ApplicationRecord

  belongs_to :user
  belongs_to :friend, class_name: "User"
  validates :friend_id, uniqueness: { scope: :user_id }



end

app/models/like.rb
class Like < ApplicationRecord

belongs_to :user
belongs_to :restaurant

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader
  belongs_to :category#, optional: true
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end


  def is_liked?(user)
   self.liked_users.include?(user)
  end

  # def favorites_count
  #  self.favorites_users.count=self.favorites.size
  #  self.save
  # end
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   validates_presence_of :name, :email
  #  :intro, :avatar

    mount_uploader :avatar, AvatarUploader
    has_many :comments, dependent: :restrict_with_error
    has_many :restaurants, through: :comments


    has_many :favorites, dependent: :destroy
    has_many :favorited_restaurants, through: :favorites, source: :restaurant

    has_many :likes, dependent: :destroy
    has_many :liked_restaurants, through: :likes, source: :restaurant

    has_many :followships, dependent: :destroy
    has_many :followings, through: :followships

    has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
    has_many :followers, through: :inverse_followships, source: :user

    has_many :friendships, dependent: :destroy
    has_many :friends, through: :friendships

    has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
    has_many :inverse_friends, through: :inverse_friendships, source: :user



    def admin?
       self.role == "admin"
    end

    def following?(user)
      self.followings.include?(user)
    end

    def all_friends
      (friends + inverse_friends).uniq
    end

    def friend?(user)
      # self.friends.include?(user)
      all_friends.include?(user)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

   

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
     devise_parameter_sanitizer.permit(:account_update, keys: [:name])
   end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
       @restaurant = Restaurant.find(params[:restaurant_id])
       @comment = @restaurant.comments.build(comment_params)
       @comment.user = current_user
      # @comment.save!
      # redirect_to restaurant_path(@restaurant)
      if @comment.save
        flash[:notice]= "Message saved"
        redirect_to restaurant_path(@restaurant)
      else
        flash.now[:alert]= @comment.errors.full_messages.each{|msg| msg.class}
        @restaurant = Restaurant.find(params[:restaurant_id])
        redirect_to restaurant_path(@restaurant, comment_params)
      end

    end

    def destroy
        @restaurant = Restaurant.find(params[:restaurant_id])
        @comment = Comment.find(params[:id])

        if current_user.admin?
          @comment.destroy
          redirect_to restaurant_path(@restaurant)
        end
      end


    private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :friend_list]


  def index

    @users = User.all
  end


  def show

    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.restaurants
    @followings = @user.followings
    @followers = @user.followers
  end

  def edit

     unless @user == current_user
       redirect_to user_path(@user)
     end
  end


  def update

     if @user.update_attributes(user_params)
       redirect_to user_path(@user)
     else
       render :action => :edit
     end
  end


  def friend_list

      @friends = @user.all_friends

  end



  private

     def set_user
        @user = User.find(params[:id])
      end

     def user_params
       params.require(:user).permit(:name, :intro, :avatar)
     end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>




     <!-- 導覽列 -->
          <nav class="navbar navbar-default">
            <div class="container-fluid">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>

                <%= link_to "餐廳評論網", root_path, class: "navbar-brand" %>
              </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="pull-right text-right nav navbar-nav">
                  <% if current_user %>
                  <% if current_user.admin? %>
                 <li><%= link_to 'Admin後台', admin_restaurants_path %></li>
                 <% end %>
                  <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
                  <li><%= link_to 'Profile', user_path(current_user) %></li>
                  <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
                  <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
                  <% else %>
                  <li><%= link_to('註冊', new_user_registration_path) %></li>
                  <li><%= link_to('登入', new_user_session_path) %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </nav>

          <% if flash[:notice] %>
              <div class="container">
                <div class="row">

                   <div class="alert alert-success alert-dismissible" role="alert">
                 <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <%= notice %>
               </div>
                 </div>
               </div>
               <% end %>

               <% if flash[:alert] %>
               <div class="container">
                 <div class="row">

                   <div class="alert alert-danger alert-dismissible" role="alert">
                   <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                   <%= alert %>
                  </div>
                 </div>
               </div>
            <% end %>


    <%= yield %>
  </body>
</html>

app/views/shared/_favorite.html.erb
<% if restaurant.is_favorited?(current_user) %>
  <%= link_to 'Unfavorite', unfavorite_restaurant_path(restaurant), method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to 'Favorite', favorite_restaurant_path(restaurant), method: :post, class: "btn btn-primary" %>
<% end %>

app/views/shared/_follow.html.erb
<% if user != current_user %>
    <% if current_user.following?(user) %>

     <%= link_to 'Unfollow', followship_path(user), method: :delete, class: "btn btn-primary" %>
    <% else %>

     <%= link_to 'Follow', followships_path(following_id: user), method: :post, class: "btn btn-info" %>
    <% end %>
  <% end %>

app/views/shared/_friend.html.erb
<% if user != current_user %>
  <% if current_user.friend?(user)%>
    <%= link_to 'Unfriend', friendship_path(user), method: :delete, class: "btn btn-default" %>
   <% else %>
    <%= link_to 'Friend', friendships_path(friend_id: user), method: :post, class: "btn btn-success" %>
   <% end %>
<% end %>

app/views/shared/_like.html.erb
<% if restaurant.is_liked?(current_user) %>
  <%= link_to 'Unlike', unlike_restaurant_path(restaurant), method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to 'Like', like_restaurant_path(restaurant), method: :post, class: "btn btn-primary" %>
<% end %>

app/views/shared/_restaurant_list.html.erb
<% @restaurants.each do |restaurant| %>
  <div class="col-sm-6 col-md-4">
    <div class="restaurant-item">
      <%= image_tag restaurant.image, class: "img-responsive center-block" %>
      <div class="caption">
        <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
        <p class="label label-default"><%= restaurant.category.name %><p>
        <p><%= truncate(restaurant.description, length: 80) %></p>
        <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
        <%= render partial: "shared/like", locals: {restaurant: restaurant} %>
      </div>
    </div>
  </div>
<% end %>


<div class="text-center">
  <%= paginate @restaurants %>
</div>